### ISSUE TITLE
fedlab==1.2.0 is not compatible with the repo

### ISSUE THREAD

**Issue by Haosonn** [dunzeng/StoCFL#1]
It seems fedlab==1.2.1 is the correct version with only a change works, and there are more unmatched imports in other versions
```python
from fedlab.core.client.scale.trainer import SerialTrainer
# Changed to
from fedlab.core.client import SerialTrainer
```

**Comment by dunzeng** [comment]
Thanks for noticing.

**Comment by dunzeng** [comment]
Thanks again for your notification.

We have reorganized our codes. And, this issue should be solved.
